// Autogenerated from Pigeon (v1.0.18), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by NativeApi.
NSObject<FlutterMessageCodec> *NativeApiGetCodec(void);

@protocol NativeApi
- (void)setValueValue:(NSString *)value error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void NativeApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<NativeApi> *_Nullable api);

NS_ASSUME_NONNULL_END
