// Autogenerated from Pigeon (v1.0.18), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "pigeon.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary<NSString *, id> *wrapResult(id result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = @{
        @"code": (error.code ? error.code : [NSNull null]),
        @"message": (error.message ? error.message : [NSNull null]),
        @"details": (error.details ? error.details : [NSNull null]),
        };
  }
  return @{
      @"result": (result ? result : [NSNull null]),
      @"error": errorDict,
      };
}
static id GetNullableObject(NSDictionary* dict, id key) {
  id result = dict[key];
  return (result == [NSNull null]) ? nil : result;
}



@interface NativeApiCodecReader : FlutterStandardReader
@end
@implementation NativeApiCodecReader
@end

@interface NativeApiCodecWriter : FlutterStandardWriter
@end
@implementation NativeApiCodecWriter
@end

@interface NativeApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation NativeApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[NativeApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[NativeApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *NativeApiGetCodec() {
  static dispatch_once_t sPred = 0;
  static FlutterStandardMessageCodec *sSharedObject = nil;
  dispatch_once(&sPred, ^{
    NativeApiCodecReaderWriter *readerWriter = [[NativeApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}


void NativeApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<NativeApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.NativeApi.setValue"
        binaryMessenger:binaryMessenger
        codec:NativeApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setValueValue:error:)], @"NativeApi api (%@) doesn't respond to @selector(setValueValue:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_value = args[0];
        FlutterError *error;
        [api setValueValue:arg_value error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
